[package]
name = "vulcany"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = { version = "*", features = ["linked"] }
vk-mem = "*"
raw-window-handle = "*"
image = "*"
bytemuck = {version = "*", features = ["derive"]}
memoffset = "*"

[dev-dependencies]
winit = "*"
